platform :ios, '8.0’

target ‘FLS’ do


pod 'JKCategories'
pod 'JPush'
pod 'MJRefresh'
pod 'Masonry'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'GPUImage'
pod 'SDWebImage/GIF'
pod 'AFNetworking'
pod 'MJExtension'

end
